#!/usr/bin/env bash

# stop on errors
set -e


# setup fancy-pants colors
__RAINBOWPALETTE="1"

function __colortext()
{
  echo -e " \e[$__RAINBOWPALETTE;$2m$1\e[0m"
}

function echogreen() 
{
  echo $(__colortext "$1" "32")
}

function echored() 
{
  echo $(__colortext "$1" "31")
}

function echoblue() 
{
  echo $(__colortext "$1" "34")
}

function echopurple() 
{
  echo $(__colortext "$1" "35")
}

function echoyellow() 
{
  echo $(__colortext "$1" "33")
}

function echocyan() 
{
  echo $(__colortext "$1" "36")
}


# cleanup and exit trapping
function cleanup {
    echo -e "\n"
    echoyellow "Exiting..."
    exit 0
}

trap 'cleanup' SIGINT SIGTERM ERR


# prepare for asking them what mode they're in
declare -a available_modes=("Developer" "Remote")

# start the prompting
echogreen "Choose only one. You must choose. But choose wisely."
PS3="Select your environment mode:"
# https://unix.stackexchange.com/questions/513466/bash-ignoring-sigint-trap-when-select-loop-is-running
set -o posix
select d in "${available_modes[@]}"; do
  echocyan "You have chosen... wisely: ${d}"
  yadm config local.class ${d}
  chosen_mode=$(yadm config local.class)
  break
done
set +o posix

# Install apt-get packages
system_type=$(uname -s)
if [[ "$system_type" = "Linux" && -r "$HOME/.requirements.apt-get" ]]; then
	echo -e ".requirements.apt-get file detected..."
	echogreen "Would you like to install these apt-get packages? (Y/n): "
	read prompt
	if [[ "${prompt}" == 'Y' || "${prompt}" == 'y' || "${prompt}" == '' ]]; then
    echoyellow "Updating apt-get package sources"
    sudo apt-get update --fix-missing
    echoyellow "Updating apt-get bundle"
    < "$HOME/.requirements.apt-get" xargs sudo apt-get install -y
  fi
fi

# Install homebrew if it's missing
if ! command -v brew >/dev/null 2>&1; then
  echo -e "No homebrew detected..."
  echogreen "Would you like to install homebrew? (Y/n): "
  read prompt
  if [[ "${prompt}" == 'Y' || "${prompt}" == 'y' || "${prompt}" == '' ]]; then
    echoyellow "Installing homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    # we need these available to use brew below, but their .bashrc will have it in each new shell
    eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
  fi
fi

# Install their brew packages
if [[ -r "$HOME/.Brewfile" ]]; then
  echo -e ".Brewfile detected..."
  echogreen "Would you like to install these brew packages? (Y/n): "
  read prompt
  if [[ "${prompt}" == 'Y' || "${prompt}" == 'y' || "${prompt}" == '' ]]; then
    echoyellow "Updating homebrew bundle"
    brew bundle --global
  fi
fi

# Install python pips if there's a python3
if command -v python3 >/dev/null 2>&1; then
  if [[ -r "$HOME/.requirements.pip" ]]; then
    echo -e ".requirements.pip file detected..."
    echogreen "Would you like to install these python pips? (Y/n): "
    read prompt
    if [[ "${prompt}" == 'Y' || "${prompt}" == 'y' || "${prompt}" == '' ]]; then
      echoyellow "Updating pip bundle"
      pip3 install -r "$HOME/.requirements.pip"
    fi
  fi
fi

# More bootstrapy things
if [[ "${chosen_mode}" = "Developer" ]]; then

  if command -v python3 >/dev/null 2>&1; then
    if [[ "$system_type" = "Linux" && -r /usr/bin/python ]]; then
      echo -e "Python3 detected..."
      echogreen "You have python3 installed. Would you like to remove the default system python link? (Y/n): "
      read prompt
      if [[ "${prompt}" == 'Y' || "${prompt}" == 'y' || "${prompt}" == '' ]]; then
        echoyellow "Removing default python link"
        sudo rm /usr/bin/python
      fi
    fi
  fi

  if [[ "$system_type" = "Linux" ]]; then

    # Setup docker
    if ! command -v docker >/dev/null 2>&1; then
      echo -e "No docker detected..."
      echogreen "Would you like to install docker? (Y/n): "
      read prompt
      if [[ "${prompt}" == 'Y' || "${prompt}" == 'y' || "${prompt}" == '' ]]; then
        echoyellow "Installing docker"
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        sudo usermod -aG docker $USER
        docker --version
        rm get-docker.sh

        echored "You need to logout and log back in. After login, you can restart the bootstrap process with: yadm bootstrap"

      fi
    fi

    # Setup docker-compose
    if ! command -v docker-compose >/dev/null 2>&1; then
      echo -e "No docker-compose detected..."
      echogreen "Would you like to install docker-compose? (Y/n): "
      read prompt
      if [[ "${prompt}" == 'Y' || "${prompt}" == 'y' || "${prompt}" == '' ]]; then
        echoyellow "Installing docker-compose"
        sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version
      fi
    fi

    # Setup dnsmasq for docker to use
    if ! grep 10.0.2.2 /etc/hosts >/dev/null; then

      echo -e "No /etc/hosts entries detected for loopback interface..."
      echogreen "You're missing a 10.0.2.2 entry in your /etc/hosts. Would you like modify and it now? (Y/n): "
      read prompt
      if [[ "${prompt}" == 'Y' || "${prompt}" == 'y' || "${prompt}" == '' ]]; then
        echoyellow "Modifying /etc/hosts"
        sudo bash -c "echo '10.0.2.2 wes.decisio.work wes-simulator.decisio.work wes-api.decisio.work wes-mcui.decisio.work wes-mcapi.decisio.work wes-canonic.decisio.work wes-reliant.decisio.work wes-reliant-viewer.decisio.work' >> /etc/hosts"
        echoyellow "Restarting dnsmasq"
        sudo service dnsmasq restart
        ping -c 1 wes.decisio.work
      fi

    fi

    # Point docker to host loopback for dns
    if [[ ! -r /etc/docker/daemon.json ]]; then

      echo -e "No /etc/docker/daemon.json entry detected for loopback interface..."
      echogreen "You're missing a 10.0.2.2 entry in your /etc/docker/daemon.json. Would you like modify and add it now? (Y/n): "
      read prompt
      if [[ "${prompt}" == 'Y' || "${prompt}" == 'y' || "${prompt}" == '' ]]; then
        echoyellow "Modifying /etc/docker/daemon.json"
        sudo bash -c "echo '{\"dns\": [\"10.0.2.2\", \"8.8.8.8\"]}' > /etc/docker/daemon.json"
        echoyellow "Restarting docker"
        sudo service docker restart
        docker run --rm -it busybox ping wes.decisio.work
      fi

    fi

  fi

  # Get the compose completion stuff in place
  # https://docs.docker.com/compose/completion/
  if command -v docker-compose >/dev/null 2>&1; then
    [[ ! -r "$(brew --prefix)/etc/bash_completion.d/docker-compose" ]] && curl -L https://raw.githubusercontent.com/docker/compose/1.26.2/contrib/completion/bash/docker-compose -o $(brew --prefix)/etc/bash_completion.d/docker-compose
  fi

elif [[ "${chosen_mode}" = "Remote" ]]; then
    echo "Currently nothing else bootstrap for Remote!"
fi

# Rewards
if command -v figlet >/dev/null 2>&1 && command -v lolcat >/dev/null 2>&1; then
  echo "Watch out." | figlet | lolcat
  echo "We got a developer over here." | figlet | lolcat
fi
echo "All done! Just restart your shell or source ~/.bashrc"